### ISSUE TITLE
1.20.1 client crash

### ISSUE THREAD

**Issue by oof100200** [teaconmc/XKDeco#29]
Crash log: https://pastebin.com/Q7qEcYsm
XeKr's Decoration-1.20.1-Forge-0.5.0.jar

**Comment by Snownee** [comment]
but it works on my machine 🥺

**Comment by oof100200** [comment]
> but it works on my machine 🥺

https://pastebin.com/Eva1xhXP
still crash in 0.5.1 version

**Comment by oof100200** [comment]
> but it works on my machine 🥺

i have tested it, It looks incompatible with Swampier Swamps mod.

**Comment by Snownee** [comment]
![image](https://github.com/teaconmc/XKDeco/assets/16059084/fcc227d3-4fe5-4f9f-b277-c363c173cf2f)
or it's not?

**Comment by oof100200** [comment]
> ![image](https://private-user-images.githubusercontent.com/16059084/324395825-fcc227d3-4fe5-4f9f-b277-c363c173cf2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NzY1MjYsIm5iZiI6MTcxMzc3NjIyNiwicGF0aCI6Ii8xNjA1OTA4NC8zMjQzOTU4MjUtZmNjMjI3ZDMtNGZlNS00ZjlmLWIyNzctYzM2M2MxNzNjZjJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDA4NTcwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzNDk0ZDkzZDI2NjFhOWIyN2FkZWM0NmYxZTE2ZTQ0Mzc0ODhkMmRmN2ZmYTAzNTkzYmFhMmYxMTg2YTY2MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Oi1mBPAfvxquD_bKrrQlf7I5iryjBVTS75pbYysTKXM) or it's not?

idk, But the game didn't crash until I deleted it.

**Comment by oof100200** [comment]
> ![image](https://private-user-images.githubusercontent.com/16059084/324395825-fcc227d3-4fe5-4f9f-b277-c363c173cf2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3OTAzNzIsIm5iZiI6MTcxMzc5MDA3MiwicGF0aCI6Ii8xNjA1OTA4NC8zMjQzOTU4MjUtZmNjMjI3ZDMtNGZlNS00ZjlmLWIyNzctYzM2M2MxNzNjZjJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDEyNDc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiNzEyZDJiNTY3NTA1MDRkNjUyN2JhM2M2Yzg2ZTNlOTU4OTM1ZjU3MjIwNjY5MTE1Y2RhMTYyMDg1M2NkODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KEFxBAKaeWElfrPFHkxZSvCMYyH2PpuMd4KYadLxHOk) or it's not?

new crashlog when i open creative inventory : https://pastebin.com/3B4MTRb2

**Comment by Snownee** [comment]
I guess the only thing you can do is removing mods until it stops crashing

**Comment by oof100200** [comment]
> I guess the only thing you can do is removing mods until it stops crashing

I think so, but it doesn't happen with version 0.4.1 XD

**Comment by Snownee** [comment]
There's also not as much new content as in 0.4.1

**Comment by oof100200** [comment]
> 也没有 0.4.1 那么多新内容

Yeah, Can I send you my modpack for testing?

**Comment by Snownee** [comment]
better not. I've got a lot of other things to do

**Comment by oof100200** [comment]
> better not. I've got a lot of other things to do

Fine, You're absolutely right. Have a nice day.
