### ISSUE TITLE
Mod version 0.5.2 crashes

### ISSUE THREAD

**Issue by dajiuji** [teaconmc/XKDeco#30]
Module version: XKDeco-Forge-1.20-0.4.1 (normal operation)
[minecraft-exported-logs-2024-04-21T01-07-54.log](https://github.com/teaconmc/XKDeco/files/15049152/minecraft-exported-logs-2024-04-21T01-07-54.log)

Module version: XeKr's Decoration-1.20.1-Forge-0.5.2 (not working properly)
[minecraft-exported-logs-2024-04-21T01-12-32.log](https://github.com/teaconmc/XKDeco/files/15049154/minecraft-exported-logs-2024-04-21T01-12-32.log)

**Comment by Snownee** [comment]
but it works on my machine 🥺

**Comment by HidaSharker** [comment]
It certainly works for you, but it doesn't work for me either, given that I have shaders, Embeddium & a few more mods.

**Comment by dajiuji** [comment]
> 但它可以在我的机器上运行

**Comment by dajiuji** [comment]
> 但它可以在我的机器上运行🥺

实话说，这个模组很有问题呀，在159个模组的情况下会与不知名模组冲突导致所有模组无法正常加载，在筛选之后79个模组的情况下，还会出现一些奇奇怪怪的bug，比如创造模式的部分物品标签页会消失（直接没有了，按不到），部分标签页还在只是图标不显示了。比如斜栅栏模组（DiagonalFences）会出现斜着可以连接，正着却不能。角色周围莫名出现鬼火特效（机械动力里，缠魂钟的特效），但我身上明明没有任何物品。以上问题在去除XK‘deco以后消失。这个模组之前是用MCreator制作的，可能与之有关。

**Comment by Snownee** [comment]
但是，宝宝，你要我怎么在只提供模组列表的情况下给你找出159个模组里的问题？我不是传说里的老中医，可以给你悬丝诊脉。如果你想报告物品标签页消失的问题，那就要说清楚和哪个模组在一起才会导致这个问题，以此类推，好吗？😊

**Comment by dajiuji** [comment]
> 但是，宝宝，你要我怎么在只提供模组列表的情况下给你找出159个模组里的问题？我不是传说里的老中医，可以给你悬丝诊脉。如果你想报告物品标签第消失的问题，那么要说清楚和哪个模组在一起才会导致这个问题，以此类推，好吗？😊

唉，那抱歉啊，我可能要下个星期才有时间测了

**Comment by adozenlionsroaring** [comment]
I'm getting a crash too, with 0.5.4. Here is my crash report, which also contains a list of all the mods I have installed. I'm hoping that someone who is better at reading logs than me can figure out which one it is that is causing the incompatibility, but if not I will attempt to remove them one by one until I pinpoint the problematic combinations:

[latest-client.txt](https://github.com/teaconmc/XKDeco/files/15137493/latest-client.txt)

**Comment by Snownee** [comment]
> I'm getting a crash too, with 0.5.4. Here is my crash report, which also contains a list of all the mods I have installed. I'm hoping that someone who is better at reading logs than me can figure out which one it is that is causing the incompatibility, but if not I will attempt to remove them one by one until I pinpoint the problematic combinations:
> 
> [latest-client.txt](https://github.com/teaconmc/XKDeco/files/15137493/latest-client.txt)

try updating Every Compat
