### ISSUE TITLE
Missing Textures

### ISSUE THREAD

**Issue by TheUntamed** [teaconmc/XKDeco#32]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

0.6.3

### Modloader version

Forge: 47.2.30

### [IMPORTANT] If bug:

- [X] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

I have multiple missing textures when I look at the mods content in JEI/EMI but also if I take any of those items into my inventory or place them.
![Screenshot_3](https://github.com/teaconmc/XKDeco/assets/48363903/360c3c34-2729-4c5d-8431-c869c8d53d58)
![Screenshot_4](https://github.com/teaconmc/XKDeco/assets/48363903/4646285e-4707-43ea-bc4c-f742beee544a)
![Screenshot_5](https://github.com/teaconmc/XKDeco/assets/48363903/7b4c7968-b751-4b53-8748-b61d653f4b8e)

**Comment by Snownee** [comment]
please read this: https://www.curseforge.com/minecraft/mc-mods/xks-decoration
