### ISSUE TITLE
Incompatibility between XeKR and Gregtech Modern

### ISSUE THREAD

**Issue by MeiNanita** [teaconmc/XKDeco#34]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

0.8.0

### Modloader version

Forge: 47.3.5

### [IMPORTANT] If bug:

- [X] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### [IMPORTANT] If bug: The **latest.log** file, not the crash report

https://pastebin.com/kMisB2Gb

### Issue description

Minecraft crashes whenever following 2 mods get loaded together:
GTCEu Modern - version 1.3.1
XK's Decoration - version 0.8.0

Result:
> The game crashed whilst initializing game
> Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered

Interestingly enough, using
GTCEu Modern - version 1.3.1
XK's Decoration - version 0.6.4

does work though, but anything beyond version 0.6.4 crashes.

**Comment by Snownee** [comment]
could you try installing the latest version of Kiwi?

**Comment by MeiNanita** [comment]
Still same result unfortunately

Mods used:
GTCEu Modern - version 1.3.1
XK's Decoration - version 0.8.0
Kiwi - version 11.8.20

latest.log :
https://pastebin.com/EjnVvYxy

**Comment by Snownee** [comment]
I have uploaded a new version. hopefully fixes the problem

**Comment by MeiNanita** [comment]
Unfortunately the issue still persists

Mods used:
GTCEu Modern - version 1.3.1
XK's Decoration - version 0.8.1
Kiwi - version 11.8.20

latest.log :
https://pastebin.com/3iJhkcss

**Comment by Snownee** [comment]
do you have the crash report?

**Comment by MeiNanita** [comment]
Sure do!
Crash-report : 
https://pastebin.com/2iuXmzVB
