### ISSUE TITLE
与journeymap冲突,沃的天

### ISSUE THREAD

**Issue by NayaCcR** [teaconmc/XKDeco#36]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

0.8.3

### Modloader version

fabric loader 0.16.5,fabric api 0.92.2

### [IMPORTANT] If bug:

- [X] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### [IMPORTANT] If bug: The **latest.log** file, not the crash report

https://paste.iin0.cn/?2f206b0f221efbd9#EdSQY8qS4y7BN3J6KbahsNdMs6msGzE1Kg6guVyCjzPX

### Issue description

发现一个很神奇的bug,似乎是mixin冲突,旅行地图和xk装饰放在一起会崩溃,日志会指向journeymap,显示两个与fabric-screen-layers在一起的方法错误,我尝试了许多个journeymap版本,还是一样的结果,游戏启动使用jdk21

**Comment by Snownee** [comment]
please report to journeymap
